package az.ultra.edumanmvc.enums;

import lombok.Getter;

@Getter
public enum SqlStatements {


    STUDENT_INFO_QUERY("SELECT * FROM TABLE(SYSTEM.GET_STUDENT_INFO())"),

    UPDATE_STUDENT_LIST("UPDATE EDUMAN_COMMON.TEST_PERSONS_KHAZAR TPK SET TPK.NAME = ? , TPK.SURNAME = ? , TPK.MIDDLE_NAME = ? WHERE TPK.ID = ?"),

    GET_STUDENT_LIST("""
                SELECT *
            FROM (
                SELECT
                    TPK.ID,
                    TPK.NAME,
                    TPK.SURNAME,
                    TPK.MIDDLE_NAME,
                    ROW_NUMBER() OVER (ORDER BY TPK.ID) AS row_num
                FROM
                    EDUMAN_COMMON.TEST_PERSONS_KHAZAR TPK
                WHERE
                    LOWER(TPK.NAME) LIKE '%' || ? || '%'
            ) numbered_rows
            WHERE
                row_num > ? AND row_num <= ?
            """),

    GET_STUDENT_BY_ID("SELECT TPK.ID, TPK.NAME, TPK.SURNAME, TPK.MIDDLE_NAME FROM EDUMAN_COMMON.TEST_PERSONS_KHAZAR TPK WHERE TPK.ID = ?"),

    DELETE_STUDENT_BY_ID("DELETE EDUMAN_COMMON.TEST_PERSONS_KHAZAR TPK WHERE TPK.ID = ?"),

    SAVE_STUDENT("{CALL EDUMAN_COMMON.INSERT_STUDENT( ?, ?, ?, ?, ?, ? )}"),

    GET_PERSON_LIST("SELECT CP.ID,CP.NAME,CP.SURNAME,CP.MIDDLE_NAME,CP.SEX,CP.COM_PERSON_UNIQ_ID FROM EDUMAN_COMMON.COM_PERSONS CP WHERE ROWNUM < 500"),

    GET_STUDENTS("SELECT CP.ID,CP.NAME,CP.SURNAME,CP.MIDDLE_NAME,CP.SEX,CP.COM_PERSON_UNIQ_ID FROM EDUMAN_COMMON.COM_PERSONS CP INNER JOIN EDUMAN_MANAGEMENT.MAN_STUDENTS MS ON CP.ID = MS.COM_PERSON_ID WHERE ROWNUM < 500"),

    SEARCH_QUERY("SELECT TPK.ID, TPK.NAME, TPK.SURNAME, TPK.MIDDLE_NAME FROM EDUMAN_COMMON.TEST_PERSONS_KHAZAR TPK WHERE LOWER(TPK.NAME) LIKE ");

    private final String query;

    SqlStatements(String query) {
        this.query = query;
    }
}