package az.ultra.edumanmvc.enums;

import lombok.Getter;

@Getter
public enum SqlStatements {


    STUDENT_INFO_QUERY("SELECT * FROM TABLE(SYSTEM.GET_STUDENT_INFO())"),

    UPDATE_STUDENT_LIST("UPDATE EDUMAN_COMMON.TEST_PERSONS_KHAZAR TPK SET TPK.NAME = ? , TPK.SURNAME = ? , TPK.MIDDLE_NAME = ? WHERE TPK.ID = ?"),

    GET_STUDENT_LIST("SELECT TPK.ID, TPK.NAME, TPK.SURNAME, TPK.MIDDLE_NAME FROM EDUMAN_COMMON.TEST_PERSONS_KHAZAR TPK"),

    GET_STUDENT_BY_ID("SELECT TPK.ID, TPK.NAME, TPK.SURNAME, TPK.MIDDLE_NAME FROM EDUMAN_COMMON.TEST_PERSONS_KHAZAR TPK WHERE TPK.ID = ?"),

    DELETE_STUDENT_BY_ID("DELETE EDUMAN_COMMON.TEST_PERSONS_KHAZAR TPK WHERE TPK.ID = ?"),

    SAVE_STUDENT("{CALL EDUMAN_COMMON.INSERT_STUDENT( ?, ?, ?, ?, ?, ? )}");

    private final String query;

    SqlStatements(String query) {
        this.query = query;
    }
}